openapi: 3.0.0
info:
  title: Domain Search Tools
  version: '1.0'
  description: 'WHOIS, name servers, suggestions, availability, aftermarket, etc. This is the "simple + cheap" version for $0.0001/request. More endpoints coming soon. Please see our advanced premium tools: "Domain Suggestions TLDs" and "Domain Availability Bulk". Documentation at https://besta.domains/api'
  termsOfService: 'https://besta.domains/terms'
  contact:
    url: 'https://paulshorey.com'
    name: Paul Shorey
servers:
  - url: ' http://142.93.251.57'
paths:
  /v1/whois:
    parameters: []
    get:
      summary: WHOIS record + Expiration date of domain
      tags: []
      responses:
        '404':
          description: User Not Found
      operationId: v1-whois
      description: 'Entire WHOIS text, if available, AND the expiration date (YYYY-M-D) parsed from that text. Some TLDs'' (registries'') WHOIS records are more useful than others. https://besta.domains/api'
      parameters:
        - schema:
            type: string
          in: query
          name: domain
          description: 'domain name + TLD (no spaces) (ex: example.com) Documentation at https://besta.domains/api'
          required: true
components:
  schemas: {}
