openapi: 3.0.0
info:
  title: Manage Your Account
  version: '1.0'
  description: ''
  termsOfService: 'https://besta.domains/terms'
  contact:
    name: Paul Shorey
    url: paulshorey.com
servers:
  - url: api.besta.domains
paths:
  /v1/contact:
    get:
      summary: Contact Form
      tags:
        - v1
      responses: {}
      operationId: Contact Form
      description: Send contact form directly from front-end. Uses Captcha to block spam.
components:
  schemas: {}
tags:
  - name: v1
