openapi: 3.0.0
info:
  title: Manage Your Account
  version: '1.0'
  description: Contact form backend. More coming soon.
  termsOfService: 'https://besta.domains/terms'
  contact:
    name: Paul Shorey
    url: paulshorey.com
servers:
  - url: 'http://142.93.251.57'
paths:
  /v1/contact:
    put:
      summary: ''
      operationId: PUT/v1/contact
      responses:
        '200':
          description: OK
      description: Send contact form directly from front-end. Uses Captcha to block spam.
      tags:
        - v1
components:
  schemas: {}
tags:
  - name: v1
